---
title: "Exploratory Analysis"
output: html_document
---

## How Basketball has changed in the NBA Over the Years. Who Does it Best?

### Authors

- Jack Ly (jaly1203@uw.edu)

### Date

Spring 2024

### Abstract

The way that basketball has been played in the NBA has changed greatly over the course of history, whether that be from various rule changes to overall strategy. What I want to figure out with this project is how exactly the game has changed over the years and how much it has affected the game on a more personal level. To do this, I plan to analyze various stat differentials between different seasons, and which team have adapted best over the years.

### Keywords

NBA, Basketball, Statistics

### Introduction  

Basketball, especially in the NBA, has gone through many significant transformations since the beginning. These changes include many things like strategy, rules changes, players roles, advancements, and more. The main thing that I want to identify is what changes occurred and how they affected the current NBA. This question is the main motivation for the entire project and it aims to highlight the old and current trends in basketball in the NBA. As with any game, knowing how the game has changed is incredibly important and necessary for analyzing who the best teams/players really are. This goes to the next question. Which teams have performed best from each era of the NBA? The best teams are capable of adapting to the current game and keeping up with the competition in order to stay competitive and on top of the rest of the league. This can be argued with player dominance and how strategy just did not matter in the face of certain players, however it should be noted that building a team around a dominant player is also a strategy as well as double/triple teaming certain players. The last question that I wish to ask is how player flexibility has changed overall, as certain players like Jokic have redefined in recent time how to play center.

### Related Work  

Describe your topic and related work in this space. You must include 3 citations to related work (URLs to similar work, high quality articles from the popular press, research papers, etc. ) Please use a standard citation style of your choice. (at least 200 words)

### The Dataset

Where did you find the data? Please include a link to the data source  

- https://www.kaggle.com/datasets/rodneycarroll78/nba-stats-1980-2024 (MAIN LINK TO ALL CSVs)
- https://www.kaggle.com/datasets/rodneycarroll78/nba-stats-1980-2024?select=Team+Summaries.csv (TEAM SUMMARY)
- https://www.kaggle.com/datasets/rodneycarroll78/nba-stats-1980-2024?select=Team+Totals.csv (TEAM TOTAL)

Who collected the data?  

- Rodney Carroll

How was the data collected or generated?  

- Statistics were pulled and aggregated into different CSVs from Basketball Reference.

Why was the data collected?  

- To record various seasonal stats and accolades of both players and teams.

How many observations (rows) are in your data?  

- 1254 (TEAM SUMMARY)
- 1845 (TEAM TOTAL)

How many features (columns) are in the data?  

- 29 (TEAM SUMMARY)
- 28 (TEAM TOTAL)

What, if any, ethical questions or questions of power do you need to consider when working with this data?  

- Not really any questions of power per se since this data is largely just for sports analysis, however it is important to note that data is objective, but what one individual gets from the data changes from person to person, so it really is on me to put forth the best product I can to avoid pushing false narratives.

What are possible limitations or problems with this data?   (at least 200 words)

- 

### Implications

Assuming you answer your research questions, briefly describe the expected or possible implications for technologists, designers, and policymakers. (at least 150 words)

### Limitations & Challenges
What challenges or limitations might you need to address with your project idea more broadly? Briefly discuss. (at least 150 words)

### Summary Information

Write a summary paragraph of findings that includes the 5 values calculated from your summary information R script

### Table

Include a table of aggregate information

Describe why you included the table and what information it reveals

### Chart 1

Include a chart

Describe why you chose this chart and what information it reveals

Here's an example of how to run an R script inside an RMarkdown file:

``````{r, echo = FALSE, code = readLines("chart1_example.R")}
``````

### Chart 2

Include a chart

Describe why you chose this chart and what information it reveals

### Chart 3

Include a chart

Describe why you chose this chart and what information it reveals
